In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv('./data/train.csv')
train_df.head()

x         y color
0  0.129270  1.979720   red
1 -0.380831  1.693519   red
2  0.718693  1.791793   red
3  0.722922  0.620655   red
4 -0.432689  0.541550   red

In [3]:
# check the different color options
color_list = train_df.color.unique()
print(train_df.color.unique())

['red' 'blue' 'green' 'teal' 'orange' 'purple']


In [4]:
# convert the colors into numbers so we can use them in our model
color_dict = {'red':0, 'blue':1, 'green':2, 'teal':3, 'orange':4, 'purple':5}
train_df['color'] = train_df.color.apply(lambda x: color_dict[x])
print(train_df.color.unique()) # re-test

np.random.shuffle(train_df.values) # shuffle the data

[0 1 2 3 4 5]


In [5]:
train_df.head()

x         y  color
0  0.129270  1.979720      0
1 -0.380831  1.693519      0
2  0.718693  1.791793      0
3  0.722922  0.620655      0
4 -0.432689  0.541550      0

Convert dataframe into numpy array to be used in the network

In [6]:
train_input_values = np.column_stack((train_df.x.values, train_df.y.values))
train_output_values = train_df.color.values

print("x and y values:\n", train_input_values[0:25])
print("\ncolor values:\n",train_output_values[0:25])

x and y values:
 [[ 0.1292705   1.97972044]
 [-0.38083105  1.69351856]
 [ 0.71869315  1.79179293]
 [ 0.72292171  0.62065463]
 [-0.43268856  0.54154953]
 [-0.19876169  0.27999977]
 [-0.65267906  1.77737626]
 [ 0.83289698  0.95064167]
 [ 0.58753543  1.45618939]
 [ 0.09390232  1.18035608]
 [-0.95111908  0.75528412]
 [ 0.51010662  0.11397083]
 [ 0.13772848  1.42035302]
 [-0.04770738  0.74682975]
 [-0.96549485  1.73937582]
 [ 0.55232197  1.84853073]
 [ 0.89560012  1.44949938]
 [-0.73840724  1.92928426]
 [ 0.2846534   1.29895239]
 [ 0.6706838   1.52057473]
 [-0.78192933  1.25234959]
 [-0.2827387   0.8663863 ]
 [-0.42308408  1.40472446]
 [ 0.83283379  0.34069105]
 [ 0.37876341  1.49807382]]

color values:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [7]:
model = keras.Sequential([
    keras.layers.Dense(32, input_shape = (2,), activation = 'relu'), # 32 neurons in our first hidden layer
    keras.layers.Dense(32, activation = 'relu'), # add another layer
    keras.layers.Dropout(0.2), # add a dropout (20%)
    keras.layers.Dense(6, activation = 'sigmoid')]) # output layer of 6, representing the colors

model.compile(optimizer = 'adam',
              loss = keras.losses.SparseCategoricalCrossentropy(from_logits = True),
              metrics = ['accuracy'])

model.fit(train_input_values, train_output_values, batch_size = 4, epochs = 10)

Train on 6000 samples
Epoch 1/10
6000/6000 [==============================] - 2s 386us/sample - loss: 1.3529 - accuracy: 0.6383
Epoch 2/10
6000/6000 [==============================] - 2s 307us/sample - loss: 1.2003 - accuracy: 0.6940
Epoch 3/10
6000/6000 [==============================] - 2s 297us/sample - loss: 1.1783 - accuracy: 0.7255
Epoch 4/10
6000/6000 [==============================] - 2s 313us/sample - loss: 1.1592 - accuracy: 0.7675
Epoch 5/10
6000/6000 [==============================] - 2s 315us/sample - loss: 1.1448 - accuracy: 0.8247
Epoch 6/10
6000/6000 [==============================] - 2s 307us/sample - loss: 1.1273 - accuracy: 0.9068
Epoch 7/10
6000/6000 [==============================] - 2s 313us/sample - loss: 1.1071 - accuracy: 0.9500
Epoch 8/10
6000/6000 [==============================] - 2s 322us/sample - loss: 1.0978 - accuracy: 0.9583
Epoch 9/10
6000/6000 [==============================] - 2s 302us/sample - loss: 1.0927 - accuracy: 0.9597
Epoch 10/10
6000/6000 [=

Now we use our model on the test data

In [8]:
test_df = pd.read_csv('./data/test.csv')
test_df['color'] = test_df.color.apply(lambda x: color_dict[x]) # remember to convert the colors to ints
test_df.head()

x         y  color
0 -0.173868  1.381852      0
1 -0.724148  1.883008      0
2 -0.423915  1.408297      0
3 -0.650162  1.296067      0
4  0.957933  0.633111      0

In [9]:
test_input_values = np.column_stack((test_df.x.values, test_df.y.values))
test_output_values = test_df.color.values

In [10]:
model.evaluate(test_input_values, test_output_values)

1200/1200 [==============================] - 0s 123us/sample - loss: 1.0741 - accuracy: 0.9717


[1.07408584912618, 0.9716667]

In [14]:
# test a co-ordinate to see if it gives us the correct output
print(np.round(model.predict(np.array([[0, 3]]))))
print(color_list)
print("Therefore the co-ordinate values of (0, 3) will give us a purple dot.")

[[0. 0. 0. 0. 0. 1.]]
['red' 'blue' 'green' 'teal' 'orange' 'purple']
Therefore the co-ordinate values of (0, 3) will give us a purple dot.
